.MODEL SMALL
.STACK 100H
.DATA
; ARRAY DB 100 DUP('$')
LARGEST_NUM DB 0H
PROMP_MSG_FOR_INPUT_ARRAY DB 'ENTER YOUR ARRAY OF ELEMENTS: $'
PROMP_MSG_FOR_OUTPUT DB 0ah,0dh,'LARGEST NUMBER IS: $'
; LEN_OF_ARRAY DW 0H
.CODE
MAIN PROC

    MOV AX,@DATA
    MOV DS,AX

    MOV AH,9
    LEA DX,PROMP_MSG_FOR_INPUT_ARRAY
    INT 21H
    
    MOV AH,1
    XOR SI,SI
    
    INPUT:
        INT 21H
        CMP AL,0DH
        JE EXIT_FROM_INPUT
        
        CMP AL,LARGEST_NUM
        JLE SKIP
        MOV LARGEST_NUM,AL
        SKIP:
        INC SI
    JMP INPUT
    EXIT_FROM_INPUT:

    ;SHOW LARGEST NUMBER
    MOV AH,9
    LEA DX,PROMP_MSG_FOR_OUTPUT
    INT 21H

    MOV AH,2
    MOV DL,LARGEST_NUM
    INT 21H

    ;DOS EXIT
    MOV AH,4CH
    INT 21H

MAIN ENDP
END MAIN